### ISSUE TITLE
"This item is not available in your country" on Google play store

### ISSUE THREAD

**Issue by NilsIrl** [mozilla-mobile/guardian-vpn-android#247]
I'm in the UK and I can't download the Mozilla VPN app.

I'm not sure if it's because the MozillaVPN app has been disabled in the UK or if it's because google believes I'm in another country.

**Comment by rlr** [comment]
Interesting. UK is set to available in the Play Store dashboard.

<img width="918" alt="Screen Shot 2020-10-28 at 8 30 08 PM" src="https://user-images.githubusercontent.com/36629/97510993-62310f00-195c-11eb-99e8-8022e1d194e3.png">

**Comment by NilsIrl** [comment]
Ok, it seems that my country was set to another one. But considering Google's policy it would really be best if there was no restriction at all

![image](https://user-images.githubusercontent.com/26231126/97559311-2d14d300-19d5-11eb-856e-6d83e15e69c5.png)
![photo_2020-10-29_10-58-40](https://user-images.githubusercontent.com/26231126/97559975-030fe080-19d6-11eb-915d-16c4286b4bf3.jpg)
