### ISSUE TITLE
"VPN Connected" notification only arrives *when the VPN disconnects*, on my Garmin 645 Music watch

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/guardian-vpn-android#259]
STR:
 (1) Have a Garmin watch, configured to show you notifications from your Android apps on your phone.
 (2) Open the Mozilla VPN app and click the slider to connect.
 (3) Wait a little bit (optional), and then click the slider again to disconnect.

ACTUAL RESULTS:
- When I connect to the VPN, no notification shows up on my watch.
- When I **disconnect** from the VPN, then a notification shows up on my watch -- but the notification incorrectly says "VPN Connected" (when in fact I'm now disconnected)

EXPECTED RESULTS:
To the extent that our notifications are sent to smart watches, we should make sure they show the right message.

(I'm guessing this has to do with us inadvertently misusing some piece of the Android persistent-notification API.)

**Comment by rlr** [comment]
@dholbert Thanks for the report. What version are you on?

**Comment by dholbert** [comment]
Release Version 2.0.3

**Comment by dholbert** [comment]
(I wonder if maybe our "post-a-new-notification" and/or VPN-disconnection code is inadvertently changing the status of our preexisting notification, in a way that makes it be considered important & worthy-of-sending-to-a-watch, in Android's mind?)

**Comment by dholbert** [comment]
I do see a burst of logcat activity when I disconnect, including `(main - NotificationHandler) Show notification` which sounds conceivably like something that could be improperly "promoting" the currently-showing notification. Emphasis added with `***` lines:
```
02-22 13:48:00.349 D mozillavpn: (main - MozillaVPN) VPN tunnel deactivation
02-22 13:48:00.349 D mozillavpn: (main|controller - TaskControllerAction) TaskControllerAction created for deactivation
02-22 13:48:00.349 D mozillavpn: (main - MozillaVPN) Scheduling task:  TaskControllerAction
02-22 13:48:00.349 D mozillavpn: (main - MozillaVPN) Tasks:  1
02-22 13:48:00.349 D mozillavpn: (main|controller - TaskControllerAction) TaskControllerAction run
02-22 13:48:00.349 D mozillavpn: (controller - Controller) Deactivation 4
02-22 13:48:00.350 D mozillavpn: (controller - Controller) Setting state: 5
02-22 13:48:00.354 D mozillavpn: (main - StatusIcon) Show notification
02-22 13:48:00.355 D mozillavpn: (networking - ConnectionHealth) Connection state changed
02-22 13:48:00.355 D mozillavpn: (networking - ConnectionHealth) ConnectionHealth deactivated
02-22 13:48:00.355 D mozillavpn: (networking - PingHelper) PingHelper deactivated
02-22 13:48:00.355 D mozillavpn: (captiveportal - CaptivePortalDetection) Controller state changed
02-22 13:48:00.355 D mozillavpn: (networking - ConnectionDataHolder) state changed
02-22 13:48:00.355 D mozillavpn: (networking - ConnectionDataHolder) Resetting the data
02-22 13:48:00.355 D mozillavpn: (networking - ConnectionDataHolder) Updating IP address
02-22 13:48:00.356 D mozillavpn: (networking - NetworkRequest) Network request created
02-22 13:48:00.356 D mozillavpn: (main - SystemTrayHandler) Update context menu
***
02-22 13:48:00.357 D mozillavpn: (main - NotificationHandler) Show notification
***
02-22 13:48:00.357 D mozillavpn: (networking - ConnectionCheck) Stopping a connection check
02-22 13:48:00.357 D mozillavpn: (networking - PingHelper) PingHelper deactivated
02-22 13:48:00.357 D mozillavpn: (android - AndroidController) deactivation
```

It's not until over a second later that I see another burst of logcat output that contains the actual text of the "Disconnected" message that we are presumably intending to show as the notification at this point:
```
02-22 13:48:01.937 D mozillavpn: (controller - TimerController) TimerController - Timeout: 4
02-22 13:48:01.937 D mozillavpn: (controller - Controller) Disconnected from state: 5
02-22 13:48:01.937 D mozillavpn: (networking - ConnectionCheck) Stopping a connection check
02-22 13:48:01.937 D mozillavpn: (networking - PingHelper) PingHelper deactivated
02-22 13:48:01.938 D mozillavpn: (controller - Controller) Setting state: 1
02-22 13:48:01.941 D mozillavpn: (main - StatusIcon) Show notification
02-22 13:48:01.944 D mozillavpn: (networking - ConnectionHealth) Connection state changed
02-22 13:48:01.944 D mozillavpn: (networking - ConnectionHealth) ConnectionHealth deactivated
02-22 13:48:01.944 D mozillavpn: (networking - PingHelper) PingHelper deactivated
02-22 13:48:01.944 D mozillavpn: (captiveportal - CaptivePortalDetection) Controller state changed
02-22 13:48:01.944 D mozillavpn: (networking - ConnectionDataHolder) state changed
02-22 13:48:01.945 D mozillavpn: (networking - ConnectionDataHolder) Resetting the data
02-22 13:48:01.945 D mozillavpn: (networking - ConnectionDataHolder) Updating IP address
02-22 13:48:01.945 D mozillavpn: (main - SystemTrayHandler) Update context menu
***
02-22 13:48:01.946 D mozillavpn: (main - NotificationHandler) Show notification
02-22 13:48:01.946 D mozillavpn: (android - AndroidNotificationHandler) Send notification -  Disconnected from USA, San Jose, CA
***
```

**Comment by dholbert** [comment]
FWIW, I recall seeing this recently, before the recent 2.7.0 upgrade.

But I just re-tested with 2.7.0 and I'm not seeing this issue anymore, because now *no* Mozilla VPN connected/disconnected notifications show up on my watch at all.  The connected/disconnected notification now seems to be classified as "silent" (as shown in my Android tray); I think maybe that's new, and I suspect/wonder if that's why they don't end up showing up on my watch now?

Anyway, I'm happy for them not-to-show-up on the watch.   This bug was focused on us inadvertently showing a notification that was incorrect, and now that we're not doing that, this seems to have been effectively fixed. :)
